import Head from 'next/head';
// Components
import Hero from '../components/Hero/Hero';
import Coins from '../components/Coins/Coins';
import TrendingCoins from '../components/TrendidngCoins/TrendingCoins';

export default function Home({ coins, trending }) {
  return (
    <div>
      <Head>
        <title>Crypto World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <Hero />
      {/* Coins List */}
      <Coins coins={coins}/>
      {/* Trending Cois */}
      <TrendingCoins trending={trending}/>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const coins = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=true').then(
    (res) => res.json()
  );

  const trending = await fetch('https://api.coingecko.com/api/v3/search/trending').then(
    (res) => res.json()
  );

  return{
    props: {
      coins,
      trending
    }
  }
}